# Generated by Django 2.0.5 on 2018-05-31 05:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='administrator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='expert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='normal_user',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=64)),
                ('user_passwd', models.CharField(max_length=32)),
                ('point', models.IntegerField(null=True)),
                ('type', models.CharField(max_length=16)),
                ('image', models.ImageField(null=True, upload_to='')),
                ('introduction', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='expert',
            name='expert_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.normal_user'),
        ),
        migrations.AddField(
            model_name='administrator',
            name='administrator_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.normal_user'),
        ),
    ]
